# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 9.0
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release

    # Test
    - name: Test
      run: dotnet test --no-build --verbosity normal --configuration Release --logger "trx;LogFileName=test_results.trx" --results-directory TestResults

    # Output
    - name: Tests result 🪄📊
      if: ${{ !cancelled() }}
      uses: dorny/test-reporter@v2
      with:
        name: 'Test Results'
        path: 'TestResults/*.trx'
        reporter: dotnet-trx
        
    - name: Tests result 🪄📂
      if: ${{ !cancelled() }}
      uses: actions/upload-artifact@v4
      with:
        name: Tests result
        path: TestResults
